'use strict';
let BASE_CFG = {
	IMG_ASSET: {
		misc: {url: 'images/misc.png', images: null}, // 预加载资源放入 images 内
	},
	UI: {
		TOP_GUIDE: {
			x: 2,
			y: 2,
			radius: 4,
			name: 'top_guide',
			text: "顶部引导提示区域",
			font: "bold 30pt Arial",
			style: "rgba(255, 0, 0, 1)",
			valign: "center",
			halign: "center",
    	transparent: true,
    	opacity: 0.8,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		MIDDLE_GUIDE: {
			x: 2,
			y: 250,
			radius: 4,
			name: 'mid',
			text: " 欢迎关注 H53D",
		  font: "italic bold 16pt Calibri",
			style: "rgba(255,0, 0, 1)",
			valign: "center",
			halign: "center",
    	transparent: true,
    	opacity: 0.6,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		BOTTOM_GUIDE: {
			x: 2,
			y: 250,
			text: "底部引导提示区域",
			name: 'right',
			radius: 4,
		  font: "italic bold 16pt Calibri",
			style: "rgba(255,0, 0, 1)",
			valign: "center",
			halign: "center",
    	transparent: true,
    	opacity: 0.8,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		LEFT_GUIDE: {
			x: 100,
			y: 250,
			radius: 4,
			name: 'left',
			text: "左边引导提示区域",
			style: "rgba(200,255, 0, 1)",
			font: "italic bold 16 Arial",
			valign: "center",
			halign: "center",
    	transparent: true,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		CENTER_GUIDE: {
			x: 100,
			y: 250,
			radius: 4,
			name: 'mid',
			text: "欢迎关注 H53D",
			style: "rgba(200,255, 0, 1)",
			font: "italic bold 16 Arial",
			valign: "center",
			halign: "center",
    	transparent: true,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		RIGHT_GUIDE: {
			x: 100,
			y: 250,
			text: "右边引导提示区域",
			name: 'right',
			radius: 4,
			font: "italic bold 16 Arial",
			style: "rgba(200,255, 0, 1)",
			valign: "center",
			halign: "center",
    	transparent: true,
    	images: {url: "images/misc.png", x: 24, y: 36, width: 72, height: 48},
		},
		HUD: {
			x: 180,
			y: 20,
			width: 80,
			height: 36,
			pad: 4,
			text: "HUD INFO",
			enableHit: false,
			name: "tip",
			font: "20px Arial",
			style: "rgba(255, 0, 0, 1)",
			valign: "center",
			halign: "center",
    	transparent: true,
		},
		BTN_START: {
			x: 100,
			y: 50, // 260,
			width: 30,
			height: 32,
			pad: 8,
			enableHit: true,
			text: " 开 始 ",
			name: "start",
			font: "24px Arial",
			style: "rgba(200, 255, 0, 1)",
    	transparent: true,
    	images: {url: "images/misc.png", x: 120, y: 6, width: 39, height: 24},
		},
		BTN_CLOSE: {
			show: false,
			enableHit: true,
			x: 25,
			y: 40,
			width: 24,
			height: 32,
			pad: 8,
			text: " 关 闭 ",
			name: "help",
			font: "20px Arial",
			style: "rgba(200,255, 0, 1)",
    	transparent: true,
    	opacity: 1.0,
    	images: {url: "images/misc.png", x: 414, y: 78, width: 16, height: 16},
		},
		BTN_AVATA: {
			show: false,
			enableHit: true,
			x: 25,
			y: 90,
			width: 24,
			height: 32,
			pad: 8,
			text: " head pic ",
			name: "sound",
			font: "20px Arial",
			style: "rgba(200, 255, 0, 1)",
    	transparent: true,
    	opacity: 1.0,
    	image: null,  // 头像不是合成图
		},

};
module.exports = BASE_CFG;
